master:
  # Used for label app.kubernetes.io/component
  componentName: "jenkins-master"
  image: "jenkins/jenkins"
  tag: "2.277.4-lts"
  adminPassword: "dynatrace"
  #serviceType: "NodePort"
  #nodePort: 31000
  serviceType: ClusterIP
  ingress:
    enabled: true
    hostName: jenkins.INGRESS_PLACEHOLDER
    # certManager: true
    # annotations:
    #   kubernetes.io/ingress.class: "nginx"    
    #   cert-manager.io/issuer: "letsencrypt-staging"
    #   ingress.kubernetes.io/secure-backends: true
    #   kubernetes.io/tls-acme: true
    # tls:    
    # - hosts:    
    #   - JENKINS_INGRESS_PLACEHOLDER
    #   secretName: jenkins.local-tls 
  containerEnv:
    - name: GITHUB_USER_EMAIL
      value: GITHUB_USER_EMAIL_PLACEHOLDER
    - name: GITHUB_ORGANIZATION
      value: GITHUB_ORGANIZATION_PLACEHOLDER
    - name: GITHUB_USER_NAME
      value: GITHUB_USER_NAME_PLACEHOLDER
    - name: GITHUB_PERSONAL_ACCESS_TOKEN
      value: GITHUB_PERSONAL_ACCESS_TOKEN_PLACEHOLDER
    - name: GIT_REPO
      value: GIT_REPO_PLACEHOLDER
    - name: GIT_DOMAIN
      value: GIT_DOMAIN_PLACEHOLDER
    - name: GIT_PROTOCOL
      value: http
    - name: DT_TENANT_URL
      value: DT_TENANT_URL_PLACEHOLDER
    - name: DT_API_TOKEN
      value: DT_API_TOKEN_PLACEHOLDER
    - name: SYNTH_NODE_ID
      value: SYNTH_NODE_ID_PLACEHOLDER
    - name: VM_IP
      value: VM_IP_PLACEHOLDER
    - name: JAVA_OPTS
      value: -Djenkins.install.runSetupWizard=false
  csrf:
    defaultCrumbIssuer:
      enabled: false
      proxyCompatability: true
  installPlugins:
    - command-launcher:1.5
    - kubernetes:1.28.5
    - kubernetes-credentials-provider:0.15
    - workflow-job:2.40
    - workflow-aggregator:2.6
    - credentials-binding:1.24
    - git:4.5.2
    - google-oauth-plugin:1.0.2
    - google-source-plugin:0.4
    - performance:3.18
    - github-branch-source:2.9.3
    - job-dsl:1.77
    - pipeline-build-step:2.13
    - docker-plugin:1.2.1
    - blueocean:1.24.3
    - configuration-as-code:1.50
    - http_request:1.8.27
    - pipeline-utility-steps:2.6.1
  JCasC:
    enabled: true
    defaultConfig: false
    configScripts:
      jenkins-settings: |
        jenkins:
          agentProtocols:
          - "JNLP4-connect"
          - "Ping"
          authorizationStrategy:
            loggedInUsersCanDoAnything:
              allowAnonymousRead: false
          systemMessage: Welcome to the ACE BOX CI\CD server.  This Jenkins is configured and managed 'as code'.
          disableRememberMe: false
          numExecutors: 2
          globalNodeProperties:
          - envVars:
              env:
              - key: "GITHUB_USER_EMAIL"
                value: ${GITHUB_USER_EMAIL} #Load from Environment Variable
              - key: "GITHUB_ORGANIZATION"
                value: ${GITHUB_ORGANIZATION} #Load from Environment Variable
              - key: "GIT_REPO"
                value: ${GIT_REPO} #Load from Environment Variable
              - key: "GIT_DOMAIN"
                value: ${GIT_DOMAIN} #Load from Environment Variable
              - key: "GIT_PROTOCOL"
                value: ${GIT_PROTOCOL} #Load from Environment Variable
              - key: "DT_TENANT_URL"
                value: ${DT_TENANT_URL} #Load from Environment Variable
              - key: "DT_API_TOKEN"
                value: ${DT_API_TOKEN} #Load from Environment Variable
              - key: "SYNTH_NODE_ID"
                value: ${SYNTH_NODE_ID} #Load from Environment Variable
              - key: "VM_IP"
                value: ${VM_IP} #Load from Environment Variable
          clouds:
          - kubernetes:
              containerCapStr: "10"
              jenkinsTunnel: "jenkins-agent:50000"
              jenkinsUrl: "http://jenkins:8080"
              maxRequestsPerHostStr: "32"
              name: "kubernetes"
              namespace: "jenkins"
              serverUrl: "https://kubernetes.default"
              templates:
              - containers:
                - args: "cat"
                  command: "/bin/sh -c"
                  envVars:
                  - envVar:
                      key: "JENKINS_URL"
                      value: "http://jenkins.ace.svc.cluster.local:8080"
                  image: "jenkinsci/jnlp-slave"
                  livenessProbe:
                    failureThreshold: 0
                    initialDelaySeconds: 0
                    periodSeconds: 0
                    successThreshold: 0
                    timeoutSeconds: 0
                  name: "jenkins-slave"
                  resourceLimitCpu: "512m"
                  resourceLimitMemory: "512Mi"
                  resourceRequestCpu: "512m"
                  resourceRequestMemory: "512Mi"
                  workingDir: "/home/jenkins"
                hostNetwork: false
                label: "jenkins-slave "
                name: "jenkins-slave"
                nodeUsageMode: NORMAL
                slaveConnectTimeout: 300
                slaveConnectTimeoutStr: "300"
                serviceAccount: "default"
                yamlMergeStrategy: "override"
              - containers:
                - args: "cat"
                  command: "/bin/sh -c"
                  image: "alpine/git"
                  livenessProbe:
                    failureThreshold: 0
                    initialDelaySeconds: 0
                    periodSeconds: 0
                    successThreshold: 0
                    timeoutSeconds: 0
                  name: "git"
                  ttyEnabled: true
                  workingDir: "/home/jenkins/agent"
                label: "git"
                name: "Git"
                nodeUsageMode: NORMAL
                slaveConnectTimeout: 300
                slaveConnectTimeoutStr: "300"
                yamlMergeStrategy: "override"
              - containers:
                - alwaysPullImage: false
                  args: "cat"
                  command: "/bin/sh -c"
                  image: "dynatraceace/monaco-runner:release-v1.2.0"
                  livenessProbe:
                    failureThreshold: 0
                    initialDelaySeconds: 0
                    periodSeconds: 0
                    successThreshold: 0
                    timeoutSeconds: 0
                  name: "monaco"
                  ttyEnabled: true
                  workingDir: "/home/jenkins/agent"
                id: "5775568b-4919-442c-9644-5d386216942b"
                label: "monaco-runner"
                name: "monaco-runner"
                yamlMergeStrategy: "override"
              - containers:
                - args: "cat"
                  command: "/bin/sh -c"
                  image: "dynatraceace/ace-cicd-tools:v2.0"
                  livenessProbe:
                    failureThreshold: 0
                    initialDelaySeconds: 0
                    periodSeconds: 0
                    successThreshold: 0
                    timeoutSeconds: 0
                  name: "ace"
                  ttyEnabled: true
                  workingDir: "/home/jenkins/agent"
                hostNetwork: false
                label: "ace"
                name: "ace-cicd-tools"
                slaveConnectTimeout: 300
                slaveConnectTimeoutStr: "300"
                yamlMergeStrategy: "override"
        credentials:
          system:
            domainCredentials:
              - credentials:
                - usernamePassword:
                    username: ${GITHUB_USER_NAME} #Load from Environment Variable
                    password: ${GITHUB_PERSONAL_ACCESS_TOKEN} #Load from Environment Variable
                    description: "Github Credentials for ACE"
                    id: "git-creds-ace"
                    scope: GLOBAL
        jobs:
          - script: >
              pipelineJob('Exercise 2 - Apply all') {
                definition {
                  cpsScm {
                    scriptPath('jenkins/exercise-two.Jenkinsfile')
                    scm {
                      git {
                          remote { 
                            url('${GIT_PROTOCOL}://${GIT_DOMAIN}/${GITHUB_ORGANIZATION}/${GIT_REPO}')
                          }
                          branch('*/master')
                      }
                    }
                    lightweight()
                  }
                }
              }
          - script: >
              pipelineJob('Exercise 4 - Update config') {
                definition {
                  cpsScm {
                    scriptPath('jenkins/exercise-four.Jenkinsfile')
                    scm {
                      git {
                          remote { 
                            url('${GIT_PROTOCOL}://${GIT_DOMAIN}/${GITHUB_ORGANIZATION}/${GIT_REPO}')
                          }
                          branch('*/master')
                      }
                    }
                    lightweight()
                  }
                }
              }
          - script: >
              pipelineJob('Exercise 5 - Onboard app') {
                parameters {
                  choiceParam('Environment', ['Staging','Production'], '')
                  stringParam('App_Name', 'demo-app', 'The name of the service to deploy.')
                  stringParam('Application_URL_pattern', 'demo.app/v1/', 'The version of the service to deploy.')
                  stringParam('Kubernetes_Namespace', 'demo-app-staging', 'The image of the service to deploy.')
                  stringParam('Health_check_url', 'https://dynatrace.com', 'The version of the service to deploy.')
                  booleanParam('Skip_synthetic_monitor_deployment', false, 'Skip the deployment of the HTTP monitor')
                }
                definition {
                  cpsScm {
                    scriptPath('jenkins/exercise-five.Jenkinsfile')
                    scm {
                      git {
                          remote { 
                            url('${GIT_PROTOCOL}://${GIT_DOMAIN}/${GITHUB_ORGANIZATION}/${GIT_REPO}')
                          }
                          branch('*/master')
                      }
                    }
                    lightweight()
                  }
                }
              }
          - script: >
              pipelineJob('Exercise 7 - Linking configuration') {
                definition {
                  cpsScm {
                    scriptPath('jenkins/exercise-seven.Jenkinsfile')
                    scm {
                      git {
                          remote { 
                            url('${GIT_PROTOCOL}://${GIT_DOMAIN}/${GITHUB_ORGANIZATION}/${GIT_REPO}')
                          }
                          branch('*/master')
                      }
                    }
                    lightweight()
                  }
                }
              }
persistence:
  enabled: true
  existingClaim: "jenkins-pvc"
